# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tailor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tailor
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'tailor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tailorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end